export const ECOSYSTEM_CONFIG = [
  {
    id: "os",
    name: "OS",
    category: "INTELLIGENCE",
    description: "Operating System Intelligence",
    href: "https://os.cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "health",
    name: "Health",
    category: "INTELLIGENCE",
    description: "Health Education & Intelligence",
    href: "https://health.cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "subventii",
    name: "Subvenții",
    category: "INTELLIGENCE",
    description: "Funding Intelligence",
    href: "https://subventii.cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "credite",
    name: "Credite",
    category: "FINANCE",
    description: "Credit Intelligence",
    href: "https://credite.cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "insurance",
    name: "Insurance",
    category: "FINANCE",
    description: "Insurance Intelligence",
    href: "https://insurance.cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "homefind",
    name: "HomeFind",
    category: "REAL_ESTATE",
    description: "Real Estate Intelligence",
    href: "https://homefind.cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "aixluxury",
    name: "AiX Luxury",
    category: "REAL_ESTATE",
    description: "Luxury Real Estate Intelligence",
    href: "https://aixluxury.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "marketpulse",
    name: "Market Pulse",
    category: "INTELLIGENCE",
    description: "Market & Economic Intelligence",
    href: "https://cristianvaduva.com/market-pulse",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  },
  {
    id: "cristian",
    name: "Cristian Văduva",
    category: "PERSONAL",
    description: "Personal Brand",
    href: "https://cristianvaduva.com",
    external: true,
    target: "_blank",
    rel: "noopener noreferrer",
    verified: true,
  }
] as const;

export type EcosystemItem = typeof ECOSYSTEM_CONFIG[number];
