import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://health.cristianvaduva.com";

  const staticRoutes = [
    "",
    "/about",
    "/academy",
    "/ai-coach",
    "/analytics",
    "/community",
    "/contact",
    "/dashboard",
    "/disclaimer",
    "/discover",
    "/launch",
    "/men",
    "/onboarding",
    "/pricing",
    "/privacy",
    "/products",
    "/progress",
    "/protocols",
    "/referrals",
    "/results",
    "/support",
    "/terms",
    "/women",
  ];

  const categorySubRoutes = [
    // Skin
    "/skin",
    "/skin/acne",
    "/skin/anti-aging",
    "/skin/azelaic-acid",
    "/skin/barrier-damage",
    "/skin/barrier-repair",
    "/skin/ceramides",
    "/skin/cleansers",
    "/skin/combination-skin",
    "/skin/dark-spots",
    "/skin/dry-skin",
    "/skin/fine-lines",
    "/skin/glycolic-acid",
    "/skin/hyperpigmentation",
    "/skin/moisturizers",
    "/skin/niacinamide",
    "/skin/oily-skin",
    "/skin/peptides",
    "/skin/pigmentation",
    "/skin/retinoids",
    "/skin/retinol",
    "/skin/rosacea",
    "/skin/salicylic-acid",
    "/skin/sebum",
    "/skin/sensitive-skin",
    "/skin/serums",
    "/skin/spf",
    "/skin/sun-damage",
    "/skin/vitamin-c",
    "/skin/wrinkles",

    // Hair
    "/hair",
    "/hair/biotin",
    "/hair/curly",
    "/hair/curly-hair",
    "/hair/dandruff",
    "/hair/dry-hair",
    "/hair/hair-growth",
    "/hair/hair-loss",
    "/hair/hair-oils",
    "/hair/minoxidil",
    "/hair/oils",
    "/hair/scalp",
    "/hair/scalp-health",
    "/hair/straight",
    "/hair/straight-hair",

    // Body
    "/body",
    "/body/body-composition",
    "/body/care",
    "/body/cellulite",
    "/body/feet",
    "/body/hands",
    "/body/hydration",
    "/body/posture",
    "/body/recovery",
    "/body/stretch-marks",

    // Fitness
    "/fitness",
    "/fitness/bodybuilding",
    "/fitness/build-muscle",
    "/fitness/cardio",
    "/fitness/fat-loss",
    "/fitness/hiit",
    "/fitness/hypertrophy",
    "/fitness/lose-fat",
    "/fitness/mobility",
    "/fitness/muscle-gain",
    "/fitness/powerlifting",
    "/fitness/recovery",
    "/fitness/running",
    "/fitness/strength",

    // Nutrition
    "/nutrition",
    "/nutrition/calories",
    "/nutrition/carbs",
    "/nutrition/fat-loss",
    "/nutrition/fats",
    "/nutrition/gut-health",
    "/nutrition/healthy-fats",
    "/nutrition/hydration",
    "/nutrition/intermittent-fasting",
    "/nutrition/ketogenic-diet",
    "/nutrition/meal-plans",
    "/nutrition/mediterranean-diet",
    "/nutrition/micronutrients",
    "/nutrition/muscle",
    "/nutrition/protein",
    "/nutrition/recipes",
    "/nutrition/supplements",

    // Supplements
    "/supplements",
    "/supplements/ashwagandha",
    "/supplements/bcaa",
    "/supplements/berberine",
    "/supplements/brain-health",
    "/supplements/casein",
    "/supplements/collagen",
    "/supplements/coq10",
    "/supplements/creatine",
    "/supplements/creatine-hcl",
    "/supplements/creatine-monohydrate",
    "/supplements/eaa",
    "/supplements/electrolytes",
    "/supplements/fiber",
    "/supplements/gut-health",
    "/supplements/hormones",
    "/supplements/immune",
    "/supplements/lions-mane",
    "/supplements/magnesium",
    "/supplements/multivitamin",
    "/supplements/nmn",
    "/supplements/omega-3",
    "/supplements/post-workout",
    "/supplements/pre-workout",
    "/supplements/probiotics",
    "/supplements/protein",
    "/supplements/recovery",
    "/supplements/resveratrol",
    "/supplements/rhodiola",
    "/supplements/sleep",
    "/supplements/turmeric",
    "/supplements/vitamin-c",
    "/supplements/vitamin-d",
    "/supplements/whey",
    "/supplements/zinc",

    // Longevity
    "/longevity",
    "/longevity/biohacking",
    "/longevity/blood-sugar",
    "/longevity/cold-exposure",
    "/longevity/fasting",
    "/longevity/healthy-aging",
    "/longevity/heart-health",
    "/longevity/hormones",
    "/longevity/hrv",
    "/longevity/inflammation",
    "/longevity/nad",
    "/longevity/recovery",
    "/longevity/sauna",
    "/longevity/sleep",
    "/longevity/stress",
    "/longevity/vo2-max",

    // Science
    "/science",
    "/science/biochemistry",
    "/science/clinical-studies",
    "/science/evidence-levels",
    "/science/ewg",
    "/science/hormones",
    "/science/inci",
    "/science/ingredients",
    "/science/ingredients-database",
    "/science/longevity",
    "/science/muscle",
    "/science/muscle-protein-synthesis",
    "/science/nutrition",
    "/science/pubmed",
    "/science/research",
    "/science/research-library",
    "/science/skin",
    "/science/skin-physiology",

    // Ingredients
    "/ingredients",
    "/ingredients/azelaic-acid",
    "/ingredients/ceramides",
    "/ingredients/hyaluronic-acid",
    "/ingredients/niacinamide",
    "/ingredients/peptides",
    "/ingredients/retinol",
    "/ingredients/spf",
    "/ingredients/vitamin-c",

    // Guides
    "/guides",
    "/guides/90-day-acne-program",
    "/guides/90-day-fat-loss",
    "/guides/anti-aging-guide",
    "/guides/barrier-repair-guide",
    "/guides/beginner-skincare",
    "/guides/build-muscle",
    "/guides/clear-skin-guide",
    "/guides/evening-routine",
    "/guides/fat-loss-guide",
    "/guides/gut-health-guide",
    "/guides/hair-loss-guide",
    "/guides/healthy-skin",
    "/guides/hormonal-acne-guide",
    "/guides/how-to-build-muscle",
    "/guides/how-to-lose-fat",
    "/guides/hydration-guide",
    "/guides/hyperpigmentation-guide",
    "/guides/inflammation-guide",
    "/guides/lose-fat",
    "/guides/men",
    "/guides/mens-skincare-guide",
    "/guides/morning-routine",
    "/guides/muscle-building-nutrition-guide",
    "/guides/night-routine",
    "/guides/nutrition-for-skin-guide",
    "/guides/retinol-guide",
    "/guides/rosacea-guide",
    "/guides/sensitive-skin-guide",
    "/guides/sleep-guide",
    "/guides/sleep-optimization",
    "/guides/stress-guide",
    "/guides/supplements",
    "/guides/teen-skincare-guide",
    "/guides/teens",
    "/guides/vitamin-c-guide",
    "/guides/women",
    "/guides/womens-skincare-guide",
    "/guides/workout-skin-guide",
  ];

  const allRoutes = [...staticRoutes, ...categorySubRoutes];

  return allRoutes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date().toISOString().split("T")[0],
    changeFrequency: route === "" ? "daily" : "weekly",
    priority: route === "" ? 1.0 : route.split("/").length === 2 ? 0.8 : 0.6,
  }));
}
